### ISSUE TITLE
vcf2maf: New custom_enst argument breaks when empty

### ISSUE THREAD

**Issue by lkhilton** [LCR-BCCRC/lcr-modules#159]
V1.2 of vcf2maf can't be run without a custom_enst value for every genome build. It throws this error: 
```
Option custom-enst requires an argument
```

This is a bit of a circularity problem since you have to first run vcf2maf to find non-canonical transcripts to supply to this argument. Maybe it need an `if` statement to test if the field is empty an run a different command based on that test?

**Comment by Kdreval** [comment]
I was able to run with an empty file when testing. Can you point it to a dummy file?

**Comment by lkhilton** [comment]
Will try and report back, thanks!

**Comment by rdmorin** [comment]
If this works can we set it up and document it in the config to make it more clear that users should leave the empty/dummy file unless they replace it with their own?

**Comment by Kdreval** [comment]
Absolutely!
I did it in demo config, should have thought about the default config as well
```
        # here you can specify path to txt file with a list of custom ENST IDs that override canonical selection
        # it will be parsed to --custom-enst flag of vcf2maf
        # if no non-canonical transcript IDs to be included, leave switches empty
        # This is just an example of how to include the list of custom IDs
        switches:
            custom_enst:
              hg38: ""
              grch37: "data/custom_enst.txt"
              hs37d5: ""
```
EDITED: Not even like this, the path should be for each build. I will update it once Laura confirms it worked for her.
