### ISSUE TITLE
Specify unmatched_normal_id based on wildcard

### ISSUE THREAD

**Issue by lkhilton** [LCR-BCCRC/lcr-modules#52]
For gambl we have three different genome builds, and each will need an unmatched normal specified. I've tried implementing this a couple of ways, most recently by including this in `header.smk`: 
```
GENOME_DEFAULT_SWITCH = op.switch_on_wildcard("genome_build", {
    "grch37": "14-11247N", 
    "hg38": "BLGSP-71-06-00286-99A-01D", 
    "hs37d5": "SP116656"
})
shared_config["pairing_config"]["genome"]["unmatched_normal_id"] = GENOME_DEFAULT_SWITCH
genome_default = shared_config["pairing_config"]["genome"]["unmatched_normal_id"]
PAIRS = op.generate_pairs(SAMPLES, genome=("allow_unmatched", genome_default), mrna="no_normal")
```

I get the following error when I run the above with `snakemake -np -s src/snakemake/header.smk`: 
```
AssertionError in line 71 of /projects/rmorin/projects/gambl-repos/gambl-lhilton/src/snakemake/header.smk:
There are 0 genome samples matching the normal ID <function switch_on_wildcard.<locals>._switch_on_wildcard at 0x7fb56528a440> (instead of just one).
  File "/projects/rmorin/projects/gambl-repos/gambl-lhilton/src/snakemake/header.smk", line 71, in <module>
  File "/home/lhilton/miniconda3/lib/python3.7/site-packages/oncopipe/__init__.py", line 1254, in generate_pairs
  File "/home/lhilton/miniconda3/lib/python3.7/site-packages/oncopipe/__init__.py", line 1072, in generate_runs
```
`oncopipe` version 1.0.2
`snakemake-minimal` version 5.14.0

What can I change to get this to work?

**Comment by lkhilton** [comment]
I updated `oncopipe` to 1.0.3 and the error persists.

**Comment by rdmorin** [comment]
Is it the same error if you change it to:

```
shared_config["pairing_config"]["genome"]["unmatched_normal_id"] = GENOME_DEFAULT_SWITCH = op.switch_on_wildcard("genome_build", {
    "grch37": "14-11247N", 
    "hg38": "BLGSP-71-06-00286-99A-01D", 
    "hs37d5": "SP116656"
})

**Comment by BrunoGrandePhD** [comment]
Your instinct with using a switch here was correct. For any directive loaded by `snakemake`, it will detect that the value is a function and will call the function, including if that function is a switch. 

The issue here is that the `unmatched_normal_id` field is handled by `oncopipe` rather than `snakemake`, and I totally didn't think of the fact that `unmatched_normal_id` will need to be `genome_build`-specific. This requires an update to `oncopipe`, which I'm willing to implement tonight if this can wait until then. 

I need to think of the simplest way of addressing this, but one idea is to change the pairing config keys from `<seq_type>` (_e.g._ `genome`) to `<seq_type>--<genome_build>` (_e.g._ `genome--hg38`), just like what's already in module file names. This way, a switch won't be necessary. 

While I'm editing this part of `oncopipe`, I might simplify the pairing config in the project configuration from:
```
lcr-modules:
    _shared:
        [...]
        pairing_config:
            capture:
                unmatched_normal_id: "TCRBOA7-N-WEX"
```
To:
```
lcr-modules:
    _shared:
        [...]
        unmatched_normal_id:
            capture--grch37: "TCRBOA7-N-WEX"
```
Is this intuitive?

**Comment by lkhilton** [comment]
Yep, totally intuitive. Thanks!

**Comment by lkhilton** [comment]
To confirm (since I'm close to submitting a PR for gambl) the config would look like this, right: 
```
lcr-modules: 
  _shared: 
    repository: "src/lcr-modules/"
    lcr-scripts: "src/lcr-scripts/"
    root_output_dir: "results/"
    scratch_directory: "null"
    unmatched_normal_id:
      genome--grch37: "14-11247N" 
      genome--hg38: "BLGSP-71-06-00286-99A-01D" 
      genome--hs37d5: "SP116656"
```
